# @package _global_
hydra:
  mode: MULTIRUN
  overrides:
    task:
      - experiment.seed=10,11,12,13,14,15
      - env_id=bigfish, bossfight, caveflyer, chaser, climber, coinrun, dodgeball, fruitbot, heist, jumper, leaper, maze, miner, ninja, plunder, starpilot